// src/lib/components/ui/input/Input.svelte
<script lang="ts">
  import { Label } from 'bits-ui';
  import type { HTMLInputAttributes } from 'svelte/elements';
  import styles from './input.module.scss';
  import Icon from '../../Icon.svelte';

  interface Props extends HTMLInputAttributes {
    variant?: 'default' | 'bound' | 'duration' | 'number' | 'range';
    error?: string;
    label?: string;
    leftIcon?: string;
    rightIcon?: string;
    counter?: number;
    maxLength?: number;
    hidden?: boolean;
    fullWidth?: boolean;
    fullHeight?: boolean;
    alignRight?: boolean;
    accessory?: boolean;
    children?: any;
  }

  let {
    variant = 'default',
    error,
    label,
    leftIcon,
    rightIcon,
    counter,
    maxLength,
    hidden = false,
    fullWidth = false,
    fullHeight = false,
    alignRight = false,
    accessory = false,
    value = $bindable(''),
    type = 'text',
    placeholder,
    disabled = false,
    readonly = false,
    required = false,
    class: className = '',
    children,
    ...restProps
  }: Props = $props();

  const showCounter = $derived(counter !== undefined || maxLength !== undefined);
  const currentCount = $derived(String(value).length);

  const fieldsetClasses = [
    styles.fieldset,
    hidden && styles.hidden,
    fullWidth && styles.full,
    className
  ].filter(Boolean).join(' ');

  const inputClasses = [
    styles.input,
    variant === 'bound' && styles.bound,
    variant === 'duration' && styles.duration,
    variant === 'number' && styles.number,
    variant === 'range' && styles.range,
    alignRight && styles.alignRight,
    fullHeight && styles.fullHeight,
    accessory && styles.accessory,
    (leftIcon || rightIcon || showCounter) && styles.wrapper
  ].filter(Boolean).join(' ');
</script>

<fieldset class={fieldsetClasses}>
  {#if label}
    <Label.Root class={styles.label} for={restProps.id}>
      {label}
      {#if required}
        <span class={styles.required}>*</span>
      {/if}
    </Label.Root>
  {/if}

  {#if accessory || leftIcon || rightIcon || showCounter}
    <div class={inputClasses}>
      {#if leftIcon}
        <span class={styles.iconLeft}>
          <Icon name={leftIcon} size={16} />
        </span>
      {/if}

      <input
        bind:value
        {type}
        {placeholder}
        {disabled}
        {readonly}
        {required}
        {maxLength}
        {...restProps}
      />

      {#if rightIcon}
        <span class={styles.iconRight}>
          <Icon name={rightIcon} size={16} />
        </span>
      {/if}

      {#if showCounter}
        <span class={styles.counter}>
          {currentCount}{maxLength ? `/${maxLength}` : ''}
        </span>
      {/if}
    </div>
  {:else}
    <input
      bind:value
      class={inputClasses}
      {type}
      {placeholder}
      {disabled}
      {readonly}
      {required}
      {maxLength}
      {...restProps}
    />
  {/if}

  {#if error}
    <span class={styles.error}>{error}</span>
  {/if}

  {#if children}
    {@render children()}
  {/if}
</fieldset>

// components/common/Input/index.tsx
import React, { useEffect, useState } from 'react'
import classNames from 'classnames'
import styles from './index.module.scss'

interface Props extends React.ComponentProps<'input'> {
  bound?: boolean
  error?: string
  label?: string
  fieldsetClassName?: String
  wrapperClassName?: string
  hide1Password?: boolean
  showCounter?: boolean
}

const defaultProps = {
  bound: false,
  hide1Password: true,
  showCounter: false,
}

const Input = React.forwardRef<HTMLInputElement, Props>(function Input(
  {
    value: initialValue,
    bound,
    label,
    error,
    showCounter,
    fieldsetClassName,
    wrapperClassName,
    ...props
  }: Props,
  forwardedRef
) {
  // States
  const [value, setValue] = useState(initialValue)
  const [currentCount, setCurrentCount] = useState(() =>
    props.maxLength ? props.maxLength - (`${value}` || '').length : 0
  )

  useEffect(() => {
    setValue(initialValue)
  }, [initialValue])

  // Classes
  const fieldsetClasses = classNames(
    {
      [styles.fieldset]: true,
    },
    fieldsetClassName?.split(' ').map((className) => styles[className])
  )

  const inputWrapperClasses = classNames(
    {
      [styles.wrapper]: true,
      [styles.accessory]: showCounter,
      [styles.input]: showCounter,
      [styles.bound]: showCounter && bound,
    },
    wrapperClassName?.split(' ').map((className) => styles[className])
  )

  const inputClasses = classNames(
    {
      [styles.input]: !showCounter,
      [styles.bound]: !showCounter && bound,
    },
    !showCounter &&
      props.className?.split(' ').map((className) => styles[className])
  )
  const { defaultValue, hide1Password, ...inputProps } = props

  // Hooks
  useEffect(() => {
    if (props.maxLength)
      setCurrentCount(props.maxLength - (`${value}` || '').length)
  }, [props.maxLength, value])

  // Event handlers
  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    setValue(event.target.value)
    if (props.onChange) props.onChange(event)
  }

  // Rendering
  const input = (
    <div className={inputWrapperClasses}>
      <input
        {...inputProps}
        data-1p-ignore={props.hide1Password}
        autoComplete={props.autoComplete}
        className={inputClasses}
        type={props.type}
        name={props.name}
        placeholder={props.placeholder}
        value={value || ''}
        onBlur={props.onBlur}
        onChange={handleChange}
        maxLength={props.maxLength}
        ref={forwardedRef}
        formNoValidate
      />
      <span className={styles.counter}>{currentCount}</span>
    </div>
  )

  const fieldset = (
    <fieldset className={fieldsetClasses}>
      {label && <legend className={styles.legend}>{label}</legend>}
      {input}
      {error && <span className={styles.error}>{error}</span>}
    </fieldset>
  )

  return fieldset
})

Input.defaultProps = defaultProps

export default Input
