// components/common/Switch/index.tsx
import React from 'react'
import * as RadixSwitch from '@radix-ui/react-switch'

import classNames from 'classnames'
import styles from './index.module.scss'

interface Props
  extends React.DetailedHTMLProps<
    React.InputHTMLAttributes<HTMLInputElement>,
    HTMLInputElement
  > {
  thumbClass?: string
  onCheckedChange: (checked: boolean) => void
}

const Switch = (props: Props) => {
  const {
    checked,
    className,
    disabled,
    name,
    onCheckedChange,
    required,
    thumbClass,
    value,
  } = props

  const mainClasses = classNames({ Switch: true }, className)
  const thumbClasses = classNames({ SwitchThumb: true }, thumbClass)

  return (
    <RadixSwitch.Root
      className={mainClasses}
      checked={checked}
      name={name}
      disabled={disabled}
      required={required}
      value={value}
      tabIndex={props.tabIndex}
      onCheckedChange={onCheckedChange}
    >
      <RadixSwitch.Thumb className={thumbClasses} />
    </RadixSwitch.Root>
  )
}

export default Switch

// src/lib/components/ui/switch/Switch.svelte
<!-- Switch Component -->
<svelte:options runes={true} />
<script lang="ts">
	import { Switch as SwitchPrimitive } from 'bits-ui';
	import styles from './switch.module.scss';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	interface Props extends Omit<HTMLButtonAttributes, 'value'> {
		checked?: boolean;
		disabled?: boolean;
		required?: boolean;
		name?: string;
		value?: string;
		onCheckedChange?: (checked: boolean) => void;
		class?: string;
		thumbClass?: string;
	}

	let {
		checked = $bindable(false),
		disabled = false,
		required = false,
		name,
		value,
		onCheckedChange,
		class: className,
		thumbClass,
		...restProps
	}: Props = $props();

	$effect(() => {
		if (onCheckedChange && checked !== undefined) {
			onCheckedChange(checked);
		}
	});
</script>

<SwitchPrimitive.Root
	bind:checked
	{disabled}
	{required}
	{name}
	{value}
	class={`${styles.switch} ${className || ''}`}
	{...restProps}
>
	<SwitchPrimitive.Thumb class={`${styles.thumb} ${thumbClass || ''}`} />
</SwitchPrimitive.Root>
