// components/common/Button/index.tsx
import React from 'react'
import classNames from 'classnames'

import styles from './index.module.scss'

interface Props
  extends React.DetailedHTMLProps<
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    HTMLButtonElement
  > {
  leftAccessoryIcon?: React.ReactNode
  leftAccessoryClassName?: string
  rightAccessoryIcon?: React.ReactNode
  rightAccessoryClassName?: string
  active?: boolean
  blended?: boolean
  bound?: boolean
  floating?: boolean
  size?: 'icon' | 'small' | 'medium' | 'large'
  text?: string
}

const defaultProps = {
  active: false,
  blended: false,
  bound: false,
  floating: false,
  size: 'medium' as const,
}

const Button = React.forwardRef<HTMLButtonElement, Props>(function button(
  {
    leftAccessoryIcon,
    leftAccessoryClassName,
    rightAccessoryIcon,
    rightAccessoryClassName,
    active,
    blended,
    floating,
    bound,
    size,
    text,
    ...props
  },
  forwardedRef
) {
  const classes = classNames(
    {
      [styles.button]: true,
      [styles.active]: active,
      [styles.bound]: bound,
      [styles.blended]: blended,
      [styles.floating]: floating,
      [styles.icon]: size === 'icon',
      [styles.small]: size === 'small',
      [styles.medium]: size === 'medium' || !size,
      [styles.large]: size === 'large',
    },
    props.className?.split(' ').map((className) => styles[className])
  )

  const leftAccessoryClasses = classNames(
    {
      [styles.accessory]: true,
      [styles.left]: true,
    },
    leftAccessoryClassName?.split(' ').map((className) => styles[className])
  )

  const rightAccessoryClasses = classNames(
    {
      [styles.accessory]: true,
      [styles.right]: true,
    },
    rightAccessoryClassName?.split(' ').map((className) => styles[className])
  )

  const hasLeftAccessory = () => {
    if (leftAccessoryIcon)
      return <span className={leftAccessoryClasses}>{leftAccessoryIcon}</span>
  }

  const hasRightAccessory = () => {
    if (rightAccessoryIcon)
      return <span className={rightAccessoryClasses}>{rightAccessoryIcon}</span>
  }

  const hasText = () => {
    if (text) return <span className={styles.text}>{text}</span>
  }

  return (
    <button {...props} className={classes} ref={forwardedRef}>
      {hasLeftAccessory()}
      {hasText()}
      {hasRightAccessory()}
    </button>
  )
})

Button.defaultProps = defaultProps

export default Button

// src/lib/components/ui/button/Button.svelte
<script lang="ts">
  import { Button } from 'bits-ui';
  import Icon from '../../Icon.svelte';
  import styles from './button.module.scss';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  interface Props extends HTMLButtonAttributes {
    variant?: 'primary' | 'secondary' | 'ghost' | 'text' | 'unstyled' | 'blended' | 'bound' | 'destructive' | 'notice' | 'modal';
    size?: 'icon' | 'small' | 'medium' | 'large';
    element?: 'wind' | 'fire' | 'water' | 'earth' | 'dark' | 'light' | null;
    active?: boolean;
    floating?: boolean;
    save?: boolean;
    saved?: boolean;
    leftIcon?: string;
    rightIcon?: string;
    leftAccessoryClass?: string;
    rightAccessoryClass?: string;
    // Legacy props for compatibility
    icon?: string;
    iconPosition?: 'left' | 'right';
    iconOnly?: boolean;
    fullWidth?: boolean;
    href?: string;
    children?: any;
  }

  const {
    variant = 'primary',
    size = 'medium',
    element = null,
    active = false,
    floating = false,
    save = false,
    saved = false,
    leftIcon,
    rightIcon,
    leftAccessoryClass = '',
    rightAccessoryClass = '',
    // Legacy props
    icon,
    iconPosition = 'left',
    iconOnly = false,
    fullWidth = false,
    href,
    disabled = false,
    class: className = '',
    children,
    ...restProps
  }: Props = $props();

  // Handle legacy icon prop
  const effectiveLeftIcon = leftIcon || (icon && iconPosition === 'left' ? icon : undefined);
  const effectiveRightIcon = rightIcon || (icon && iconPosition === 'right' ? icon : undefined);

  const iconSizes = {
    icon: 16,
    small: 14,
    medium: 16,
    large: 20
  };

  const classes = variant === 'unstyled'
    ? className
    : [
        styles.button,
        styles[variant],
        styles[size],
        element && styles[element],
        active && styles.active,
        floating && styles.floating,
        save && styles.save,
        saved && styles.saved,
        iconOnly && styles.iconOnly,
        fullWidth && styles.fullWidth,
        className
      ].filter(Boolean).join(' ');

  const leftAccessoryClasses = [
    styles.accessory,
    styles.left,
    leftAccessoryClass
  ].filter(Boolean).join(' ');

  const rightAccessoryClasses = [
    styles.accessory,
    styles.right,
    rightAccessoryClass
  ].filter(Boolean).join(' ');
</script>

<Button.Root
  {href}
  {disabled}
  class={classes}
  {...restProps}
>
  {#if effectiveLeftIcon}
    <span class={leftAccessoryClasses}>
      <Icon name={effectiveLeftIcon} size={iconSizes[size]} />
    </span>
  {/if}
  {#if !iconOnly && children}
    <span class={styles.text}>
      {@render children()}
    </span>
  {/if}
  {#if effectiveRightIcon}
    <span class={rightAccessoryClasses}>
      <Icon name={effectiveRightIcon} size={iconSizes[size]} />
    </span>
  {/if}
</Button.Root>
