// src/lib/components/ui/segmented-control/RepSegment.svelte
<!-- RepSegment Component - A segment with visual content and label -->

<script lang="ts">
	import { RadioGroup as RadioGroupPrimitive } from 'bits-ui'
	import type { Snippet } from 'svelte'
	import styles from './rep-segment.module.scss'

	interface Props {
		value: string
		label: string
		class?: string
		selected?: boolean
		disabled?: boolean
		children?: Snippet
	}

	let {
		value,
		label,
		class: className,
		selected = false,
		disabled,
		children: content
	}: Props = $props()
</script>

<RadioGroupPrimitive.Item
	{value}
	{...(disabled !== undefined ? { disabled } : {})}
	class={`${styles.repSegment} ${selected ? styles.selected : ''} ${className || ''}`}
>
	{#snippet children({ checked })}
		{#if checked}
			<div class={styles.indicator}></div>
		{/if}
		<div class={styles.wrapper}>
			<div class={styles.content}>
				{@render content?.()}
			</div>
			<div class={styles.label}>{label}</div>
		</div>
	{/snippet}
</RadioGroupPrimitive.Item>

// components/reps/RepSegment/index.tsx
import React, { PropsWithChildren } from 'react'

import styles from './index.module.scss'

interface Props {
  controlGroup: string
  inputName: string
  name: string
  selected: boolean
  onClick: (event: React.ChangeEvent<HTMLInputElement>) => void
}

const RepSegment = ({ children, ...props }: PropsWithChildren<Props>) => {
  return (
    <div className={styles.segment}>
      <input
        name={props.controlGroup}
        id={props.inputName}
        value={props.inputName}
        type="radio"
        checked={props.selected}
        onChange={props.onClick}
      />
      <label htmlFor={props.inputName}>
        <div className={styles.wrapper}>
          {children}
          <div className={styles.title}>{props.name}</div>
        </div>
      </label>
    </div>
  )
}

export default RepSegment
