// components/weapon/WeaponKeySelect/index.tsx
import React, { useEffect, useState } from 'react'

import Select from '~components/common/Select'
import SelectGroup from '~components/common/SelectGroup'
import SelectItem from '~components/common/SelectItem'

import { appState } from '~utils/appState'

import styles from './index.module.scss'

// Props
interface Props {
  open: boolean
  weaponKey?: WeaponKey
  series: number
  slot: number
  onChange?: (value: WeaponKey, slot: number) => void
  onOpenChange: () => void
  onClose?: () => void
}

// Constants
const pendulumNames = [
  { en: 'Pendulum', jp: 'ペンデュラム' },
  { en: 'Chain', jp: 'チェイン' },
]

const telumaNames = [{ en: 'Teluma', jp: 'テルマ' }]
const emblemNames = [{ en: 'Emblem', jp: 'エンブレム' }]
const gauphNames = [
  { en: 'Gauph Key', jp: 'ガフスキー' },
  { en: 'Ultima Key', jp: 'ガフスキーΩ' },
  { en: 'Gate of Omnipotence', jp: 'ガフスキー' },
]

const emptyWeaponKey: WeaponKey = {
  id: 'no-key',
  granblue_id: '-1',
  series: 0,
  slot: 0,
  slug: '',
  group: 0,
  order: 0,
  name: { en: '', ja: '' },
}

const WeaponKeySelect = React.forwardRef<HTMLButtonElement, Props>(
  function useFieldSet(
    { open, weaponKey, series, slot, onChange, onOpenChange, onClose },
    ref
  ) {
    const [keys, setKeys] = useState<WeaponKey[][]>([])

    useEffect(() => {
      const keys = flattenWeaponKeys()
      const filteredKeys = filterWeaponKeys(keys)
      setKeys(groupWeaponKeys(filteredKeys))
    }, [series])

    function flattenWeaponKeys() {
      const keys: WeaponKey[] = []

      for (let setName of Object.keys(appState.weaponKeys)) {
        const set = appState.weaponKeys[setName]
        set.map((key) => keys.push(key))
      }

      return keys
    }

    function filterWeaponKeys(weaponKeys: WeaponKey[]) {
      // Filter weapon keys based on the series and slot provided
      return weaponKeys.filter(
        (key) => key.series == series && key.slot == slot
      )
    }

    function groupWeaponKeys(weaponKeys: WeaponKey[]) {
      const numGroups = Math.max.apply(
        Math,
        weaponKeys.map((key) => key.group)
      )
      let groupedKeys = []
      for (let i = 0; i <= numGroups; i++) {
        const values = weaponKeys.filter((key) => key.group == i)
        if (values.length > 0) groupedKeys[i] = values
      }

      return groupedKeys.filter(() => true)
    }

    function weaponKeyGroup(index: number) {
      ;['α', 'β', 'γ', 'Δ'].sort((a, b) => a.localeCompare(b, 'el'))

      const sortByOrder = (a: WeaponKey, b: WeaponKey) =>
        a.order > b.order ? 1 : -1

      const options =
        keys &&
        keys.length > 0 &&
        keys[index].length > 0 &&
        keys[index].sort(sortByOrder).map((item, i) => {
          return (
            <SelectItem
              key={i}
              value={item.id}
              data-granblue-id={item.granblue_id}
            >
              {item.name.en}
            </SelectItem>
          )
        })

      let name: { [key: string]: string } = {}
      if (series == 2 && index == 0) name = pendulumNames[0]
      else if (series == 2 && slot == 1 && index == 1) name = pendulumNames[1]
      else if (series === 3) name = telumaNames[0]
      else if (series === 17) name = gauphNames[slot]
      else if (series === 24) name = emblemNames[index]

      return (
        <SelectGroup
          key={index}
          label={series == 17 && slot == 2 ? name.en : `${name.en}s`}
          separator={false}
        >
          {options}
        </SelectGroup>
      )
    }

    function handleChange(value: string) {
      const keys = flattenWeaponKeys()
      const found = keys.find((key) => key.id == value)
      const weaponKey = found ? found : emptyWeaponKey
      if (onChange) onChange(weaponKey, slot)
    }

    const emptyOption = () => {
      let name = ''
      if (series === 2) name = pendulumNames[0].en
      else if (series === 3) name = telumaNames[0].en
      else if (series === 17) name = gauphNames[slot].en
      else if (series === 24) name = emblemNames[0].en

      return `No ${name}`
    }

    return (
      <Select
        key={`weapon-key-${slot}`}
        value={weaponKey ? weaponKey.id : emptyWeaponKey.id}
        open={open}
        onClose={onClose}
        onOpenChange={onOpenChange}
        onValueChange={handleChange}
        ref={ref}
        overlayVisible={false}
      >
        <SelectItem key={emptyWeaponKey.id} value={emptyWeaponKey.id}>
          {emptyOption()}
        </SelectItem>
        {Array.from(Array(keys?.length)).map((x, i) => {
          return weaponKeyGroup(i)
        })}
      </Select>
    )
  }
)

export default WeaponKeySelect

// src/lib/components/sidebar/edit/WeaponKeySelect.svelte
<script lang="ts">
	import { createQuery } from '@tanstack/svelte-query'
	import { entityQueries } from '$lib/api/queries/entity.queries'
	import type { WeaponKey } from '$lib/api/adapters/entity.adapter'
	import Select from '$lib/components/ui/Select.svelte'

	interface Props {
		/** The weapon series (determines which keys are available) */
		series: number
		/** The slot number (1, 2, or 3) */
		slot: number
		/** Currently selected weapon key ID */
		value?: string
		/** Called when selection changes */
		onchange?: (key: WeaponKey | undefined) => void
		/** Current transcendence step (for key validation) */
		transcendenceStep?: number
	}

	let { series, slot, value = $bindable(), onchange, transcendenceStep = 0 }: Props = $props()

	// Key type names based on series and slot (0-based indexing)
	const KEY_TYPE_NAMES: Record<number, Record<number, { en: string; ja: string }>> = {
		// Dark Opus (series 3)
		3: {
			0: { en: 'Pendulum', ja: 'ペンデュラム' },
			1: { en: 'Pendulum/Chain', ja: 'ペンデュラム/チェイン' }
		},
		// Draconic (series 27)
		27: {
			0: { en: 'Teluma', ja: 'テルマ' },
			1: { en: 'Teluma', ja: 'テルマ' }
		},
		// Ultima (series 13)
		13: {
			0: { en: 'Gauph Key', ja: 'ガフスキー' },
			1: { en: 'Ultima Key', ja: 'ガフスキーΩ' },
			2: { en: 'Gate of Omnipotence', ja: 'ガフスキー' }
		},
		// Astral (series 19)
		19: {
			0: { en: 'Emblem', ja: 'エンブレム' }
		},
		// Superlative (series 40)
		40: {
			0: { en: 'Teluma', ja: 'テルマ' },
			1: { en: 'Teluma', ja: 'テルマ' }
		}
	}

	// Fetch weapon keys for this series and slot
	const weaponKeysQuery = createQuery(() => entityQueries.weaponKeys({ series, slot }))

	// Get the key type name for this series/slot
	const keyTypeName = $derived(KEY_TYPE_NAMES[series]?.[slot]?.en ?? 'Key')

	// Group and sort weapon keys
	const groupedOptions = $derived.by(() => {
		const keys = weaponKeysQuery.data ?? []
		if (keys.length === 0) return []

		// Group by group property
		const groups = new Map<number, WeaponKey[]>()
		for (const key of keys) {
			const existing = groups.get(key.group) ?? []
			existing.push(key)
			groups.set(key.group, existing)
		}

		// Sort within groups and flatten
		const result: Array<{ value: string; label: string; disabled?: boolean }> = []

		// Add "No key" option first
		result.push({
			value: '',
			label: `No ${keyTypeName}`
		})

		// Add grouped keys
		for (const [, groupKeys] of [...groups.entries()].sort((a, b) => a[0] - b[0])) {
			const sorted = groupKeys.sort((a, b) => a.order - b.order)
			for (const key of sorted) {
				// Check if key requires transcendence (specific granblue_ids)
				const requiresTranscendence = [14005, 14006, 14007].includes(key.granblue_id)
				const isDisabled = requiresTranscendence && transcendenceStep < 3

				result.push({
					value: key.id,
					label: key.name.en,
					disabled: isDisabled
				})
			}
		}

		return result
	})

	// Find the full weapon key object from ID
	function findKeyById(id: string | undefined): WeaponKey | undefined {
		if (!id) return undefined
		return (weaponKeysQuery.data ?? []).find((k: WeaponKey) => k.id === id)
	}

	function handleChange(newValue: string | undefined) {
		value = newValue
		onchange?.(findKeyById(newValue))
	}
</script>

<div class="weapon-key-select">
	{#if weaponKeysQuery.isPending}
		<div class="loading">Loading keys...</div>
	{:else if weaponKeysQuery.error}
		<div class="error">Failed to load keys</div>
	{:else}
		<Select
			options={groupedOptions}
			value={value ?? ''}
			onValueChange={handleChange}
			placeholder={`Select ${keyTypeName}`}
			size="medium"
			fullWidth
			contained
		/>
	{/if}
</div>

<style lang="scss">
	@use '$src/themes/spacing' as spacing;
	@use '$src/themes/typography' as typography;

	.weapon-key-select {
		width: 100%;
	}

	.loading,
	.error {
		padding: spacing.$unit-2x;
		font-size: typography.$font-small;
		color: var(--text-tertiary);
	}

	.error {
		color: var(--text-error);
	}
</style>
