// src/lib/components/ui/select/Select.svelte
<script lang="ts" generics="T extends string | number">
  import { Select } from 'bits-ui';
  import { ChevronDown, Check } from 'lucide-svelte';
  import styles from './select.module.scss';

  interface Option {
    value: T;
    label: string;
    disabled?: boolean;
    image?: string;
  }

  interface Props {
    options: Option[];
    value?: T;
    onValueChange?: (value: T | undefined) => void;
    placeholder?: string;
    disabled?: boolean;
    variant?: 'default' | 'bound' | 'small' | 'table';
    position?: 'left' | 'right';
    fullWidth?: boolean;
    hidden?: boolean;
    name?: string;
    required?: boolean;
    class?: string;
  }

  const {
    options = [],
    value = $bindable(),
    onValueChange,
    placeholder = 'Select an option',
    disabled = false,
    variant = 'default',
    position = 'left',
    fullWidth = false,
    hidden = false,
    name,
    required = false,
    class: className = ''
  }: Props = $props();

  const selected = $derived(options.find(opt => opt.value === value));

  const triggerClasses = [
    styles.trigger,
    variant === 'bound' && styles.bound,
    variant === 'small' && styles.small,
    variant === 'table' && styles.table,
    position === 'right' && styles.right,
    position === 'left' && styles.left,
    fullWidth && styles.full,
    hidden && styles.hidden,
    disabled && styles.disabled,
    className
  ].filter(Boolean).join(' ');

  const contentClasses = [
    styles.select,
    variant === 'bound' && styles.bound
  ].filter(Boolean).join(' ');

  function handleValueChange(newValue: string | undefined) {
    if (newValue !== undefined && onValueChange) {
      onValueChange(newValue as T);
    }
  }
</script>

<Select.Root
  bind:value
  onValueChange={handleValueChange}
  {disabled}
  {name}
  {required}
>
  <Select.Trigger
    class={triggerClasses}
    data-placeholder={!selected}
  >
    {#if selected?.image}
      <img src={selected.image} alt={selected.label} />
    {/if}
    <span>{selected?.label || placeholder}</span>
    <span class={styles.icon}>
      <ChevronDown size={16} />
    </span>
  </Select.Trigger>

  <Select.Content class={contentClasses}>
    <div class={`${styles.scroll} ${styles.up}`}>
      <ChevronDown size={16} />
    </div>

    <Select.Viewport>
      {#each options as option}
        <Select.Item
          value={option.value}
          disabled={option.disabled}
          class={styles.item}
        >
          {#if option.image}
            <img src={option.image} alt={option.label} />
          {/if}
          <span>{option.label}</span>
          <Select.ItemIndicator class={styles.indicator}>
            <Check size={16} />
          </Select.ItemIndicator>
        </Select.Item>
      {/each}
    </Select.Viewport>

    <div class={`${styles.scroll} ${styles.down}`}>
      <ChevronDown size={16} />
    </div>
  </Select.Content>
</Select.Root>

// components/common/Select/index.tsx
import React, { useEffect, useState } from 'react'
import * as RadixSelect from '@radix-ui/react-select'
import classNames from 'classnames'

import Overlay from '~components/common/Overlay'

import ChevronIcon from '~public/icons/Chevron.svg'

import styles from './index.module.scss'

// Props
interface Props
  extends React.DetailedHTMLProps<
    React.SelectHTMLAttributes<HTMLSelectElement>,
    HTMLSelectElement
  > {
  open: boolean
  icon?: {
    src: string
    alt: string
  }
  trigger?: {
    bound?: boolean
    className?: string
    placeholder?: string
    size?: 'small' | 'medium' | 'large'
  }
  children?: React.ReactNode
  onOpenChange?: () => void
  onValueChange?: (value: string) => void
  onClose?: () => void
  overlayVisible?: boolean
}

const Select = React.forwardRef<HTMLButtonElement, Props>(function Select(
  props: Props,
  forwardedRef
) {
  const [open, setOpen] = useState(false)
  const [value, setValue] = useState('')

  const triggerClasses = classNames({
    [styles.trigger]: true,
    [styles.disabled]: props.disabled,
    [styles.bound]: props.trigger ? props.trigger.bound : false,
    [styles.small]: props.trigger?.size === 'small',
    [styles.medium]: !props.trigger || props.trigger?.size === 'medium',
    [styles.large]: props.trigger?.size === 'large',
  })

  const selectClasses = classNames(
    {
      [styles.select]: true,
    },
    props.className
  )

  useEffect(() => {
    setOpen(props.open)
  }, [props.open])

  useEffect(() => {
    if (props.value && props.value !== '') setValue(`${props.value}`)
    else setValue('')
  }, [props.value])

  function onValueChange(newValue: string) {
    setValue(`${newValue}`)
    if (props.onValueChange) props.onValueChange(newValue)
  }

  function onCloseAutoFocus() {
    setOpen(false)
    if (props.onClose) props.onClose()
  }

  function onEscapeKeyDown() {
    setOpen(false)
    if (props.onClose) props.onClose()
  }

  function onPointerDownOutside() {
    setOpen(false)
    if (props.onClose) props.onClose()
  }

  return (
    <RadixSelect.Root
      open={open}
      value={value !== '' ? value : undefined}
      onValueChange={onValueChange}
      onOpenChange={props.onOpenChange}
    >
      <RadixSelect.Trigger
        className={triggerClasses}
        placeholder={props.placeholder}
        ref={forwardedRef}
      >
        {props.icon ? <img alt={props.icon.alt} src={props.icon.src} /> : ''}
        <RadixSelect.Value placeholder={props.trigger?.placeholder} />
        {!props.disabled ? (
          <RadixSelect.Icon className={styles.icon}>
            <ChevronIcon />
          </RadixSelect.Icon>
        ) : (
          ''
        )}
      </RadixSelect.Trigger>

      <RadixSelect.Portal>
        <>
          <Overlay
            open={open}
            visible={props.overlayVisible != null ? props.overlayVisible : true}
          />

          <RadixSelect.Content
            className={selectClasses}
            position="popper"
            sideOffset={6}
            onCloseAutoFocus={onCloseAutoFocus}
            onEscapeKeyDown={onEscapeKeyDown}
            onPointerDownOutside={onPointerDownOutside}
          >
            <RadixSelect.ScrollUpButton
              className={classNames({
                [styles.scroll]: true,
                [styles.up]: true,
              })}
            >
              <ChevronIcon />
            </RadixSelect.ScrollUpButton>
            <RadixSelect.Viewport>{props.children}</RadixSelect.Viewport>
            <RadixSelect.ScrollDownButton
              className={classNames({
                [styles.scroll]: true,
                [styles.down]: true,
              })}
            >
              <ChevronIcon />
            </RadixSelect.ScrollDownButton>
          </RadixSelect.Content>
        </>
      </RadixSelect.Portal>
    </RadixSelect.Root>
  )
})

Select.defaultProps = {
  overlayVisible: true,
}

export default Select
